[package]
name = "banana-omen"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["Daniel Omen Lobos Aguayo"]
license = "MIT"
description = "An example package."

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
